---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - hippo.hippocampus.com
  resources:
  - hippocampuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hippo.hippocampus.com
  resources:
  - hippocampuses/finalizers
  verbs:
  - update
- apiGroups:
  - hippo.hippocampus.com
  resources:
  - hippocampuses/status
  verbs:
  - get
  - patch
  - update
